# Generated by Django 2.2 on 2020-03-01 11:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name': '部门', 'verbose_name_plural': '部门'},
        ),
        migrations.AlterModelOptions(
            name='educationbackground',
            options={'verbose_name': '教育背景', 'verbose_name_plural': '教育背景'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': '性别', 'verbose_name_plural': '性别'},
        ),
        migrations.AlterModelOptions(
            name='p_info',
            options={'ordering': ['-created_time'], 'verbose_name': '员工信息', 'verbose_name_plural': '员工信息'},
        ),
        migrations.AddField(
            model_name='p_info',
            name='phone_in_fire',
            field=models.CharField(default='110', max_length=15, verbose_name='紧急联系人电话'),
        ),
        migrations.AlterField(
            model_name='p_info',
            name='contends',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='个人经历及其他信息'),
        ),
        migrations.AlterField(
            model_name='p_info',
            name='id_number',
            field=models.CharField(max_length=10, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='p_info',
            name='job_detail',
            field=models.CharField(max_length=30, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='p_info',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='电话号码'),
        ),
    ]
