# Generated by Django 2.2 on 2020-03-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_auto_20200301_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_info',
            name='work_place',
            field=models.CharField(blank=True, default='不固定', max_length=20, verbose_name='办公地点'),
        ),
    ]
