# Generated by Django 2.2 on 2020-04-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='filename',
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='headImg',
            field=models.FileField(upload_to=''),
        ),
    ]
