# Generated by Django 2.2 on 2020-05-03 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0002_auto_20200417_1633'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
