# Generated by Django 2.2 on 2020-01-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='er_feng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producted_time', models.DateField()),
                ('producted_num', models.IntegerField()),
                ('unqualified_num', models.IntegerField()),
                ('qualified_num', models.IntegerField()),
                ('unqualified_type', models.CharField(max_length=10)),
                ('is_delete', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='error_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=10)),
                ('producted_time', models.DateField()),
                ('reason_analysis', models.TextField(max_length=50)),
                ('measure', models.TextField(max_length=100)),
                ('error_type', models.CharField(max_length=10)),
                ('putting_position', models.CharField(max_length=10)),
                ('resp_position', models.CharField(max_length=10)),
                ('curr_situation', models.CharField(max_length=10)),
                ('is_delete', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='fen_rong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producted_time', models.DateField()),
                ('producted_num', models.IntegerField()),
                ('unqualified_num', models.IntegerField()),
                ('qualified_num', models.IntegerField()),
                ('unqualified_type', models.CharField(max_length=10)),
                ('is_delete', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='fen_xuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producted_time', models.DateField()),
                ('producted_num', models.IntegerField()),
                ('unqualified_num', models.IntegerField()),
                ('qualified_num', models.IntegerField()),
                ('unqualified_type', models.CharField(max_length=10)),
                ('is_delete', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FQC_exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_date', models.DateField()),
                ('ex_num', models.IntegerField()),
                ('qualified_num', models.IntegerField()),
                ('return_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='fu_ji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producted_time', models.DateField()),
                ('producted_num', models.IntegerField()),
                ('unqualified_num', models.IntegerField()),
                ('qualified_num', models.IntegerField()),
                ('unqualified_type', models.CharField(max_length=10)),
                ('is_delete', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='hua_cheng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producted_time', models.DateField()),
                ('producted_num', models.IntegerField()),
                ('unqualified_num', models.IntegerField()),
                ('qualified_num', models.IntegerField()),
                ('unqualified_type', models.CharField(max_length=10)),
                ('is_delete', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='juan_rao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producted_time', models.DateField()),
                ('producted_num', models.IntegerField()),
                ('unqualified_num', models.IntegerField()),
                ('qualified_num', models.IntegerField()),
                ('unqualified_type', models.CharField(max_length=10)),
                ('is_delete', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='zheng_ji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producted_time', models.DateField()),
                ('producted_num', models.IntegerField()),
                ('unqualified_num', models.IntegerField()),
                ('qualified_num', models.IntegerField()),
                ('unqualified_type', models.CharField(max_length=10)),
                ('is_delete', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='zhu_ye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producted_time', models.DateField()),
                ('producted_num', models.IntegerField()),
                ('unqualified_num', models.IntegerField()),
                ('qualified_num', models.IntegerField()),
                ('unqualified_type', models.CharField(max_length=10)),
                ('is_delete', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='zhuang_pei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producted_time', models.DateField()),
                ('producted_num', models.IntegerField()),
                ('unqualified_num', models.IntegerField()),
                ('qualified_num', models.IntegerField()),
                ('unqualified_type', models.CharField(max_length=10)),
                ('is_delete', models.BooleanField(default=0)),
            ],
        ),
    ]
