# Generated by Django 2.2 on 2020-02-04 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0002_auto_20200204_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erfeng',
            name='unqualified_type',
        ),
        migrations.RemoveField(
            model_name='fenrong',
            name='unqualified_type',
        ),
        migrations.RemoveField(
            model_name='fenxuan',
            name='unqualified_type',
        ),
        migrations.RemoveField(
            model_name='fuji',
            name='unqualified_type',
        ),
        migrations.RemoveField(
            model_name='huacheng',
            name='unqualified_type',
        ),
        migrations.RemoveField(
            model_name='juanrao',
            name='unqualified_type',
        ),
        migrations.RemoveField(
            model_name='zhengji',
            name='unqualified_type',
        ),
        migrations.RemoveField(
            model_name='zhuangpei',
            name='unqualified_type',
        ),
        migrations.RemoveField(
            model_name='zhuye',
            name='unqualified_type',
        ),
        migrations.CreateModel(
            name='ZhuyeUnqualified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unqualified_num', models.IntegerField()),
                ('unqualified_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='battery.UnquaifiedType')),
            ],
        ),
        migrations.CreateModel(
            name='ZhuangPeiUnqualified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unqualified_num', models.IntegerField()),
                ('unqualified_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='battery.UnquaifiedType')),
            ],
        ),
        migrations.CreateModel(
            name='zhengjiUnqualified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unqualified_num', models.IntegerField()),
                ('unqualified_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='battery.UnquaifiedType')),
            ],
        ),
        migrations.CreateModel(
            name='JuanraoUnqualified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unqualified_num', models.IntegerField()),
                ('unqualified_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='battery.UnquaifiedType')),
            ],
        ),
        migrations.CreateModel(
            name='HuachengUnqualified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unqualified_num', models.IntegerField()),
                ('unqualified_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='battery.UnquaifiedType')),
            ],
        ),
        migrations.CreateModel(
            name='FujiUnqualified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unqualified_num', models.IntegerField()),
                ('unqualified_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='battery.UnquaifiedType')),
            ],
        ),
        migrations.CreateModel(
            name='FenxuanUnqualified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unqualified_num', models.IntegerField()),
                ('unqualified_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='battery.UnquaifiedType')),
            ],
        ),
        migrations.CreateModel(
            name='FenrongUnqualified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unqualified_num', models.IntegerField()),
                ('unqualified_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='battery.UnquaifiedType')),
            ],
        ),
        migrations.CreateModel(
            name='ErfengUnqualified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unqualified_num', models.IntegerField()),
                ('unqualified_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='battery.UnquaifiedType')),
            ],
        ),
    ]
