# Generated by Django 2.2 on 2020-02-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0004_auto_20200204_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='erfeng',
            name='procedure',
            field=models.CharField(default='二封车间', max_length=4),
        ),
        migrations.AddField(
            model_name='fenrong',
            name='procedure',
            field=models.CharField(default='分容车间', max_length=4),
        ),
        migrations.AddField(
            model_name='fenxuan',
            name='procedure',
            field=models.CharField(default='分选车间', max_length=4),
        ),
        migrations.AddField(
            model_name='fuji',
            name='procedure',
            field=models.CharField(default='负极', max_length=2),
        ),
        migrations.AddField(
            model_name='huacheng',
            name='procedure',
            field=models.CharField(default='化成车间', max_length=4),
        ),
        migrations.AddField(
            model_name='juanrao',
            name='procedure',
            field=models.CharField(default='卷绕车间', max_length=4),
        ),
        migrations.AddField(
            model_name='zhengji',
            name='procedure',
            field=models.CharField(default='正极', max_length=2),
        ),
        migrations.AddField(
            model_name='zhuangpei',
            name='procedure',
            field=models.CharField(default='装配车间', max_length=4),
        ),
        migrations.AddField(
            model_name='zhuye',
            name='procedure',
            field=models.CharField(default='注液车间', max_length=4),
        ),
    ]
