# Generated by Django 2.2 on 2020-02-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0005_auto_20200207_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshoperror',
            old_name='producted_time',
            new_name='happened_date',
        ),
        migrations.AddField(
            model_name='workshoperror',
            name='situation_description',
            field=models.TextField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='workshoperror',
            name='reason_analysis',
            field=models.TextField(max_length=100),
        ),
    ]
