# Generated by Django 2.2 on 2020-02-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0006_auto_20200207_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='erfeng',
            name='conclusion',
            field=models.TextField(default='无'),
        ),
        migrations.AddField(
            model_name='fenrong',
            name='conclusion',
            field=models.TextField(default='无'),
        ),
        migrations.AddField(
            model_name='fenxuan',
            name='conclusion',
            field=models.TextField(default='无'),
        ),
        migrations.AddField(
            model_name='fuji',
            name='conclusion',
            field=models.TextField(default='无'),
        ),
        migrations.AddField(
            model_name='huacheng',
            name='conclusion',
            field=models.TextField(default='无'),
        ),
        migrations.AddField(
            model_name='juanrao',
            name='conclusion',
            field=models.TextField(default='无'),
        ),
        migrations.AddField(
            model_name='zhengji',
            name='conclusion',
            field=models.TextField(default='无'),
        ),
        migrations.AddField(
            model_name='zhuangpei',
            name='conclusion',
            field=models.TextField(default='无'),
        ),
        migrations.AddField(
            model_name='zhuye',
            name='conclusion',
            field=models.TextField(default='无'),
        ),
    ]
