# Generated by Django 2.2 on 2020-02-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0007_auto_20200207_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='erfeng',
            name='qualified_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fenrong',
            name='qualified_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fenxuan',
            name='qualified_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fqctest',
            name='qualified_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fuji',
            name='qualified_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='huacheng',
            name='qualified_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='juanrao',
            name='qualified_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zhengji',
            name='qualified_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zhuangpei',
            name='qualified_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zhuye',
            name='qualified_rate',
            field=models.FloatField(default=0),
        ),
    ]
