# Generated by Django 2.2 on 2020-02-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0009_auto_20200220_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhengjiunqualified',
            name='created_time',
            field=models.DateTimeField(),
        ),
    ]
