# Generated by Django 2.2 on 2020-03-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0013_auto_20200301_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unquaifiedtype',
            options={'verbose_name': '不良类型管理', 'verbose_name_plural': '不良类型管理'},
        ),
        migrations.AlterModelOptions(
            name='zhuangpeiunqualified',
            options={'verbose_name': '装配不良信息管理', 'verbose_name_plural': '装配不良信息管理'},
        ),
        migrations.AlterField(
            model_name='erfeng',
            name='conclusion',
            field=models.TextField(default='无', verbose_name='总结'),
        ),
        migrations.AlterField(
            model_name='erfeng',
            name='is_delete',
            field=models.BooleanField(default=0, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='erfeng',
            name='procedure',
            field=models.CharField(default='二封车间', max_length=4, verbose_name='工序'),
        ),
        migrations.AlterField(
            model_name='fenrong',
            name='conclusion',
            field=models.TextField(default='无', verbose_name='总结'),
        ),
        migrations.AlterField(
            model_name='fenrong',
            name='is_delete',
            field=models.BooleanField(default=0, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='fenrong',
            name='procedure',
            field=models.CharField(default='分容车间', max_length=4, verbose_name='工序'),
        ),
        migrations.AlterField(
            model_name='fenxuan',
            name='conclusion',
            field=models.TextField(default='无', verbose_name='总结'),
        ),
        migrations.AlterField(
            model_name='fenxuan',
            name='is_delete',
            field=models.BooleanField(default=0, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='fenxuan',
            name='procedure',
            field=models.CharField(default='分选车间', max_length=4, verbose_name='工序'),
        ),
        migrations.AlterField(
            model_name='fuji',
            name='conclusion',
            field=models.TextField(default='无', verbose_name='总结'),
        ),
        migrations.AlterField(
            model_name='fuji',
            name='is_delete',
            field=models.BooleanField(default=0, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='fuji',
            name='procedure',
            field=models.CharField(default='负极', max_length=2, verbose_name='工序'),
        ),
        migrations.AlterField(
            model_name='huacheng',
            name='conclusion',
            field=models.TextField(default='无', verbose_name='总结'),
        ),
        migrations.AlterField(
            model_name='huacheng',
            name='is_delete',
            field=models.BooleanField(default=0, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='huacheng',
            name='procedure',
            field=models.CharField(default='化成车间', max_length=4, verbose_name='工序'),
        ),
        migrations.AlterField(
            model_name='juanrao',
            name='conclusion',
            field=models.TextField(default='无', verbose_name='总结'),
        ),
        migrations.AlterField(
            model_name='juanrao',
            name='is_delete',
            field=models.BooleanField(default=0, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='unquaifiedtype',
            name='unqualified_type',
            field=models.CharField(max_length=20, verbose_name='不良类型'),
        ),
        migrations.AlterField(
            model_name='workshoperror',
            name='curr_situation',
            field=models.CharField(max_length=10, verbose_name='目前状况'),
        ),
        migrations.AlterField(
            model_name='workshoperror',
            name='happened_date',
            field=models.DateField(verbose_name='发生时间'),
        ),
        migrations.AlterField(
            model_name='workshoperror',
            name='is_delete',
            field=models.BooleanField(default=0, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='workshoperror',
            name='measure',
            field=models.TextField(max_length=100, verbose_name='解决措施'),
        ),
        migrations.AlterField(
            model_name='workshoperror',
            name='product_type',
            field=models.CharField(max_length=10, verbose_name='产品型号'),
        ),
        migrations.AlterField(
            model_name='workshoperror',
            name='putting_position',
            field=models.CharField(max_length=10, verbose_name='提报工段'),
        ),
        migrations.AlterField(
            model_name='zhengji',
            name='conclusion',
            field=models.TextField(default='无', verbose_name='总结'),
        ),
        migrations.AlterField(
            model_name='zhengji',
            name='is_delete',
            field=models.BooleanField(default=0, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='zhengji',
            name='procedure',
            field=models.CharField(default='正极', max_length=2, verbose_name='工序'),
        ),
        migrations.AlterField(
            model_name='zhuangpei',
            name='conclusion',
            field=models.TextField(default='无', verbose_name='总结'),
        ),
        migrations.AlterField(
            model_name='zhuangpei',
            name='is_delete',
            field=models.BooleanField(default=0, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='zhuangpei',
            name='procedure',
            field=models.CharField(default='装配车间', max_length=4, verbose_name='工序'),
        ),
        migrations.AlterField(
            model_name='zhuye',
            name='procedure',
            field=models.CharField(default='注液车间', max_length=4, verbose_name='工序'),
        ),
    ]
