# Generated by Django 2.2 on 2020-03-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0015_auto_20200307_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erfengunqualified',
            name='created_time',
            field=models.DateField(verbose_name='产生时间'),
        ),
        migrations.AlterField(
            model_name='fenrongunqualified',
            name='created_time',
            field=models.DateField(verbose_name='产生时间'),
        ),
        migrations.AlterField(
            model_name='fenxuanunqualified',
            name='created_time',
            field=models.DateField(verbose_name='产生时间'),
        ),
        migrations.AlterField(
            model_name='fujiunqualified',
            name='created_time',
            field=models.DateField(verbose_name='产生时间'),
        ),
        migrations.AlterField(
            model_name='huachengunqualified',
            name='created_time',
            field=models.DateField(verbose_name='产生时间'),
        ),
        migrations.AlterField(
            model_name='juanraounqualified',
            name='created_time',
            field=models.DateField(verbose_name='产生时间'),
        ),
        migrations.AlterField(
            model_name='zhengjiunqualified',
            name='created_time',
            field=models.DateField(verbose_name='产生时间'),
        ),
        migrations.AlterField(
            model_name='zhuangpeiunqualified',
            name='created_time',
            field=models.DateField(verbose_name='产生时间'),
        ),
        migrations.AlterField(
            model_name='zhuyeunqualified',
            name='created_time',
            field=models.DateField(verbose_name='产生时间'),
        ),
    ]
