# Generated by Django 2.2 on 2020-05-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(max_length=500, verbose_name='住址'),
        ),
    ]
